from flask import Flask, render_template, jsonify, session, request
import random

app = Flask(__name__)
app.secret_key = "supersecretkey"

# Example: Card groups by theme (split your existing list)
FLASHCARDS = {
    "Weather": [
        {"fi": "sää", "en": "weather"},
        {"fi": "aurinko", "en": "sun"},
        {"fi": "sade", "en": "rain"},
        {"fi": "tuuli", "en": "wind"},
        {"fi": "kylmä", "en": "cold"},
        {"fi": "Millainen sää tänään on?", "en": "What is the weather like today?"},
        {"fi": "Ulkona sataa vettä.", "en": "It's raining outside."},
        {"fi": "Onko kylmä vai lämmin?", "en": "Is it cold or warm?"},
        {"fi": "helle", "en": "heat wave"},
        {"fi": "pakkas", "en": "frost"},
        {"fi": "räntä", "en": "sleet"},
        {"fi": "myrsky", "en": "storm"},
        {"fi": "sumu", "en": "fog"},
        {"fi": "kaste", "en": "dew"},
        {"fi": "raekuuro", "en": "hail shower"},
        {"fi": "sääennuste", "en": "weather forecast"},
        {"fi": "ilmasto", "en": "climate"},
        {"fi": "kosteus", "en": "humidity"},
        {"fi": "On pilvistä tänään.", "en": "It's cloudy today."},
        {"fi": "Lämpötila on miinuksen puolella.", "en": "The temperature is below zero."},
        {"fi": "Sääennuste lupaa aurinkoa.", "en": "The weather forecast promises sun."},
        {"fi": "Myrsky tulee yöllä.", "en": "The storm is coming at night."},
        {"fi": "Sumu peittää kaupungin.", "en": "Fog covers the city."},
        {"fi": "Ukkonen jyrisee.", "en": "Thunder is rumbling."},
        {"fi": "Sää muuttuu nopeasti.", "en": "The weather changes quickly."},
        {"fi": "Tänään on tosi lämmin.", "en": "It's really warm today."},
        {"fi": "Talvi on lempivuodenaikani.", "en": "Winter is my favorite season."},
        {"fi": "Kesällä on valoisaa yölläkin.", "en": "It's light even at night in summer."},
        {"fi": "Keväällä kukat alkavat kukkia.", "en": "Flowers start to bloom in spring."},
        {"fi": "Syksyllä lehdet putoavat puista.", "en": "Leaves fall from trees in autumn."},
        {"fi": "Odotan jo kesälomaa.", "en": "I'm already looking forward to summer vacation."},
        {"fi": "Lumi sulaa nopeasti keväällä.", "en": "Snow melts quickly in spring."},
        {"fi": "Aurinko laskee aikaisin talvella.", "en": "The sun sets early in winter."},
        {"fi": "Täällä sataa paljon syksyisin.", "en": "It rains a lot here in autumn."},
    ],
    "Grocery Store": [
        {"fi": "kauppa", "en": "store/shop"},
        {"fi": "maito", "en": "milk"},
        {"fi": "leipä", "en": "bread"},
        {"fi": "omena", "en": "apple"},
        {"fi": "kassa", "en": "checkout/cash register"},
        {"fi": "Missä on maito?", "en": "Where is the milk?"},
        {"fi": "Haluaisin kaksi omenaa.", "en": "I would like two apples."},
        {"fi": "Voinko maksaa kortilla?", "en": "Can I pay with a card?"},
        {"fi": "hinta", "en": "price"},
        {"fi": "raha", "en": "money"},
        {"fi": "alennus", "en": "discount"},
        {"fi": "lasku", "en": "bill"},
        {"fi": "kuitti", "en": "receipt"},
        {"fi": "pankkikortti", "en": "bank card"},
        {"fi": "käteinen", "en": "cash"},
        {"fi": "ostoskori", "en": "shopping basket"},
        {"fi": "ostoskärry", "en": "shopping cart"},
        {"fi": "Onko tämä tarjouksessa?", "en": "Is this on sale?"},
        {"fi": "Missä on kassa?", "en": "Where is the checkout?"},
        {"fi": "Voinko maksaa käteisellä?", "en": "Can I pay in cash?"},
        {"fi": "Tarvitsen kuitin.", "en": "I need a receipt."},
        {"fi": "Paljon tämä maksaa?", "en": "How much does this cost?"},
        {"fi": "Haluan palauttaa tämän.", "en": "I want to return this."},
    ],
    "Travel": [
        {"fi": "juna", "en": "train"},
        {"fi": "lentoasema", "en": "airport"},
        {"fi": "lippu", "en": "ticket"},
        {"fi": "matka", "en": "trip/journey"},
        {"fi": "bussi", "en": "bus"},
        {"fi": "aikataulu", "en": "schedule"},
        {"fi": "taksi", "en": "taxi"},
        {"fi": "laukku", "en": "bag"},
        {"fi": "hotelli", "en": "hotel"},
        {"fi": "varaus", "en": "reservation"},
        {"fi": "Missä on juna-asema?", "en": "Where is the train station?"},
        {"fi": "Tarvitsen lipun Helsinkiin.", "en": "I need a ticket to Helsinki."},
        {"fi": "Milloin bussi lähtee?", "en": "When does the bus leave?"},
        {"fi": "Onko sinulla varaus?", "en": "Do you have a reservation?"},
        {"fi": "Voinko saada taksin?", "en": "Can I get a taxi?"},
        {"fi": "Matka oli pitkä mutta mukava.", "en": "The trip was long but pleasant."},
        {"fi": "Voinko saada kaupungin kartan?", "en": "Can I have a map of the city?"},
        {"fi": "Missä pysäkki sijaitsee?", "en": "Where is the stop located?"},
        {"fi": "Kuinka kauan matka kestää?", "en": "How long does the journey take?"},
        {"fi": "Voitteko näyttää reitin?", "en": "Can you show the route?"},
        {"fi": "Onko tämä oikea bussi lentokentälle?", "en": "Is this the right bus to the airport?"},
        {"fi": "Tarvitsen aikataulun.", "en": "I need a timetable."},
        {"fi": "Jääkö tämä juna seuraavalla asemalla?", "en": "Does this train stop at the next station?"},
        {"fi": "Voinko varata lipun ennakkoon?", "en": "Can I book a ticket in advance?"},
        {"fi": "Mihin aikaan bussi lähtee?", "en": "What time does the bus leave?"},
        {"fi": "Missä vaihtaa metroa?", "en": "Where do I change for the metro?"},
    ],
    "Greetings & Introductions": [
        {"fi": "hei", "en": "hi"},
        {"fi": "moi", "en": "hello"},
        {"fi": "hyvää huomenta", "en": "good morning"},
        {"fi": "hyvää iltaa", "en": "good evening"},
        {"fi": "näkemiin", "en": "goodbye"},
        {"fi": "mitä kuuluu?", "en": "how are you?"},
        {"fi": "kiitos", "en": "thank you"},
        {"fi": "anteeksi", "en": "sorry / excuse me"},
        {"fi": "nimeni on…", "en": "my name is…"},
        {"fi": "hauska tutustua", "en": "nice to meet you"},
        {"fi": "Hei! Miten menee?", "en": "Hi! How’s it going?"},
        {"fi": "Hyvää päivää!", "en": "Good day!"},
        {"fi": "Nimeni on Alex.", "en": "My name is Alex."},
        {"fi": "Hauska tutustua!", "en": "Nice to meet you!"},
        {"fi": "Anteeksi, en ymmärrä.", "en": "Sorry, I don’t understand."},
        {"fi": "Kiitos paljon!", "en": "Thank you very much!"},
        {"fi": "Voimmeko tavata tänään?", "en": "Can we meet today?"},
        {"fi": "Tervetuloa kylään!", "en": "Welcome to visit!"},
        {"fi": "Soitan sinulle huomenna.", "en": "I'll call you tomorrow."},
        {"fi": "Missä tapaamme?", "en": "Where shall we meet?"},
        {"fi": "Kiitos seurasta!", "en": "Thank you for the company!"},
        {"fi": "Mennäänkö kahville yhdessä?", "en": "Shall we go for a coffee together?"},
        {"fi": "Anteeksi, olen myöhässä.", "en": "Sorry, I'm late."},
        {"fi": "En voi nyt puhua.", "en": "I can't talk right now."},
        {"fi": "Oli mukava nähdä sinua.", "en": "It was nice to see you."},
        {"fi": "Odotan sinua ulkona.", "en": "I'm waiting for you outside."},
    ],
    # ... CONTINUE with all other themes as above, splitting the giant list into theme blocks ...
    # ... other themes ...
    "At the Café": [
        {"fi": "kahvi", "en": "coffee"},
        {"fi": "tee", "en": "tea"},
        {"fi": "pulla", "en": "sweet bun"},
        {"fi": "kakku", "en": "cake"},
        {"fi": "maito", "en": "milk"},
        {"fi": "sokeri", "en": "sugar"},
        {"fi": "kuppi", "en": "cup"},
        {"fi": "lasi", "en": "glass"},
        {"fi": "tarjoilija", "en": "waiter/waitress"},
        {"fi": "lasku", "en": "bill/check"},
        {"fi": "Yksi kahvi, kiitos.", "en": "One coffee, please."},
        {"fi": "Haluaisin kupin teetä.", "en": "I would like a cup of tea."},
        {"fi": "Onko teillä laktoositonta maitoa?", "en": "Do you have lactose-free milk?"},
        {"fi": "Missä on vessa?", "en": "Where is the restroom?"},
        {"fi": "Saanko laskun?", "en": "Can I get the bill?"},
        {"fi": "Tämä kakku on herkullista!", "en": "This cake is delicious!"},
        {"fi": "Onko teillä kasvisvaihtoehtoja?", "en": "Do you have vegetarian options?"},
        {"fi": "Voinko saada ruokalistan?", "en": "Can I have the menu?"},
        {"fi": "Mikä on päivän annos?", "en": "What is the dish of the day?"},
        {"fi": "Voitteko suositella jotain?", "en": "Can you recommend something?"},
        {"fi": "Voinko saada veden ilman jääpaloja?", "en": "Can I have water without ice?"},
        {"fi": "Oliko kaikki kunnossa?", "en": "Was everything alright?"},
        {"fi": "Voinko maksaa laskun erikseen?", "en": "Can I pay the bill separately?"},
        {"fi": "Ruoka oli herkullista.", "en": "The food was delicious."},
        {"fi": "Kiitos ja hyvää päivänjatkoa!", "en": "Thank you and have a nice day!"},
    ],
    "Home": [
        {"fi": "koti", "en": "home"},
        {"fi": "huone", "en": "room"},
        {"fi": "keittiö", "en": "kitchen"},
        {"fi": "olohuone", "en": "living room"},
        {"fi": "makuuhuone", "en": "bedroom"},
        {"fi": "kylpyhuone", "en": "bathroom"},
        {"fi": "sänky", "en": "bed"},
        {"fi": "pöytä", "en": "table"},
        {"fi": "tuoli", "en": "chair"},
        {"fi": "lamppu", "en": "lamp"},
        {"fi": "Asun tässä talossa.", "en": "I live in this house."},
        {"fi": "Missä on keittiö?", "en": "Where is the kitchen?"},
        {"fi": "Olohuoneessa on sohva.", "en": "There is a sofa in the living room."},
        {"fi": "Makuuhuone on yläkerrassa.", "en": "The bedroom is upstairs."},
        {"fi": "Tarvitsen uuden tuolin.", "en": "I need a new chair."},
        {"fi": "Lamppu ei toimi.", "en": "The lamp doesn't work."},
        {"fi": "ovi", "en": "door"},
        {"fi": "ikkuna", "en": "window"},
        {"fi": "katto", "en": "roof"},
        {"fi": "lattia", "en": "floor"},
        {"fi": "matto", "en": "carpet"},
        {"fi": "kirjahylly", "en": "bookshelf"},
        {"fi": "sohva", "en": "sofa"},
        {"fi": "verho", "en": "curtain"},
        {"fi": "jääkaappi", "en": "fridge"},
        {"fi": "uuni", "en": "oven"},
        {"fi": "Sulje ovi, kiitos.", "en": "Close the door, please."},
        {"fi": "Avaa ikkuna.", "en": "Open the window."},
        {"fi": "Missä on jääkaappi?", "en": "Where is the fridge?"},
        {"fi": "Tarvitsen uuden maton.", "en": "I need a new carpet."},
        {"fi": "Sohva on mukava.", "en": "The sofa is comfortable."},
        {"fi": "Verhot ovat siniset.", "en": "The curtains are blue."},
        {"fi": "Asumme kolmikerroksisessa talossa.", "en": "We live in a three-story house."},
        {"fi": "Lapset leikkivät pihalla.", "en": "The children are playing in the yard."},
        {"fi": "Keittiössä on paljon valoa.", "en": "There is a lot of light in the kitchen."},
        {"fi": "Perheeni tulee vierailulle viikonloppuna.", "en": "My family is coming to visit this weekend."},
        {"fi": "Pesen pyykkiä joka lauantai.", "en": "I do laundry every Saturday."},
        {"fi": "Tarvitsemme lisää ruokaa jääkaappiin.", "en": "We need more food in the fridge."},
        {"fi": "Olen kotona iltaan asti.", "en": "I'll be home until the evening."},
        {"fi": "Vietämme aikaa yhdessä iltaisin.", "en": "We spend time together in the evenings."},
        {"fi": "Tänään on siivouspäivä.", "en": "Today is cleaning day."},
        {"fi": "Naapuri auttaa meitä usein.", "en": "The neighbor often helps us."},
    ],
    "At Work": [
        {"fi": "toimisto", "en": "office"},
        {"fi": "työ", "en": "work"},
        {"fi": "työntekijä", "en": "employee"},
        {"fi": "pomo", "en": "boss"},
        {"fi": "kokous", "en": "meeting"},
        {"fi": "tietokone", "en": "computer"},
        {"fi": "sähköposti", "en": "email"},
        {"fi": "asiakas", "en": "customer"},
        {"fi": "tauko", "en": "break"},
        {"fi": "projekti", "en": "project"},
        {"fi": "Olen töissä toimistossa.", "en": "I work in an office."},
        {"fi": "Minulla on kokous kello kymmenen.", "en": "I have a meeting at ten o’clock."},
        {"fi": "Voitko lähettää sähköpostin?", "en": "Can you send an email?"},
        {"fi": "Asiakas odottaa sinua.", "en": "The customer is waiting for you."},
        {"fi": "Pomo ei ole tänään paikalla.", "en": "The boss is not here today."},
        {"fi": "Pidetään tauko.", "en": "Let’s take a break."},
        {"fi": "Voitko tulostaa tämän asiakirjan?", "en": "Can you print this document?"},
        {"fi": "Tarvitsen apua tehtävän kanssa.", "en": "I need help with the assignment."},
        {"fi": "Voimmeko pitää kokouksen huomenna?", "en": "Can we have the meeting tomorrow?"},
        {"fi": "Onko sinulla muistiinpanot mukana?", "en": "Do you have the notes with you?"},
        {"fi": "Lähetän raportin tänään.", "en": "I'll send the report today."},
        {"fi": "Kokeen tulokset julkaistaan ensi viikolla.", "en": "The test results will be published next week."},
        {"fi": "Missä on luokkahuone numero viisi?", "en": "Where is classroom number five?"},
        {"fi": "Opettaja selittää asian uudelleen.", "en": "The teacher explains the matter again."},
        {"fi": "Tauko alkaa nyt.", "en": "The break starts now."},
        {"fi": "Projektin deadline lähestyy.", "en": "The project deadline is approaching."},
    ],
    "In the Bathroom": [
        {"fi": "suihku", "en": "shower"},
        {"fi": "kylpy", "en": "bath"},
        {"fi": "pesuallas", "en": "sink"},
        {"fi": "hammasharja", "en": "toothbrush"},
        {"fi": "hammastahna", "en": "toothpaste"},
        {"fi": "saippua", "en": "soap"},
        {"fi": "shampoo", "en": "shampoo"},
        {"fi": "pyyhe", "en": "towel"},
        {"fi": "wc", "en": "toilet"},
        {"fi": "peili", "en": "mirror"},
        {"fi": "Menetkö suihkuun?", "en": "Are you going to take a shower?"},
        {"fi": "Tarvitsen uuden hammasharjan.", "en": "I need a new toothbrush."},
        {"fi": "Missä on wc?", "en": "Where is the toilet?"},
        {"fi": "Pyyhe on märkä.", "en": "The towel is wet."},
        {"fi": "Käytän saippuaa ja shampoota.", "en": "I use soap and shampoo."},
        {"fi": "Peili on kylpyhuoneessa.", "en": "The mirror is in the bathroom."},
        {"fi": "Sulje ovi, kiitos.", "en": "Close the door, please."},
        {"fi": "Avaa ikkuna.", "en": "Open the window."},
        {"fi": "Missä on pyykkikori?", "en": "Where is the laundry basket?"},
        {"fi": "Lattia on märkä.", "en": "The floor is wet."},
    ],
    "Clothing": [
        {"fi": "paita", "en": "shirt"},
        {"fi": "housut", "en": "pants"},
        {"fi": "takki", "en": "jacket"},
        {"fi": "hame", "en": "skirt"},
        {"fi": "kengät", "en": "shoes"},
        {"fi": "sukat", "en": "socks"},
        {"fi": "hattu", "en": "hat"},
        {"fi": "käsineet", "en": "gloves"},
        {"fi": "mekko", "en": "dress"},
        {"fi": "kaulahuivi", "en": "scarf"},
        {"fi": "Missä sovituskoppi on?", "en": "Where is the fitting room?"},
        {"fi": "Haluaisin ostaa takin.", "en": "I would like to buy a jacket."},
        {"fi": "Nämä kengät ovat liian pienet.", "en": "These shoes are too small."},
        {"fi": "Onko teillä tätä paitaa toisessa koossa?", "en": "Do you have this shirt in another size?"},
        {"fi": "Tarvitsen lämpimän kaulahuivin.", "en": "I need a warm scarf."},
        {"fi": "Housut sopivat hyvin.", "en": "The pants fit well."},
        {"fi": "Onko tämä takki vedenpitävä?", "en": "Is this jacket waterproof?"},
        {"fi": "Paljonko nämä kengät maksavat?", "en": "How much do these shoes cost?"},
        {"fi": "Voitteko näyttää toisen värin?", "en": "Can you show another color?"},
        {"fi": "Tarvitsen uuden vyön.", "en": "I need a new belt."},
    ],
    "Food & Meals": [
        {"fi": "ruoka", "en": "food"},
        {"fi": "aamiainen", "en": "breakfast"},
        {"fi": "lounas", "en": "lunch"},
        {"fi": "päivällinen", "en": "dinner"},
        {"fi": "jälkiruoka", "en": "dessert"},
        {"fi": "kala", "en": "fish"},
        {"fi": "liha", "en": "meat"},
        {"fi": "vihannekset", "en": "vegetables"},
        {"fi": "peruna", "en": "potato"},
        {"fi": "riisi", "en": "rice"},
        {"fi": "Mitä haluat syödä?", "en": "What do you want to eat?"},
        {"fi": "Aamiainen on valmis.", "en": "Breakfast is ready."},
        {"fi": "Lounaaksi on kalaa ja perunoita.", "en": "For lunch, there is fish and potatoes."},
        {"fi": "Pidätkö jälkiruoasta?", "en": "Do you like dessert?"},
        {"fi": "Tämä ruoka on herkullista.", "en": "This food is delicious."},
        {"fi": "Syön usein vihanneksia ja riisiä.", "en": "I often eat vegetables and rice."},
        {"fi": "Mennään ravintolaan.", "en": "Let's go to a restaurant."},
        {"fi": "Onko ruoka gluteeniton?", "en": "Is the food gluten-free?"},
        {"fi": "Haluan kupin kahvia.", "en": "I want a cup of coffee."},
        {"fi": "Lisää sokeria, kiitos.", "en": "More sugar, please."},
    ],
    
    "At the Doctor's": [
        {"fi": "lääkäri", "en": "doctor"},
        {"fi": "sairaala", "en": "hospital"},
        {"fi": "apteekki", "en": "pharmacy"},
        {"fi": "kipu", "en": "pain"},
        {"fi": "flunssa", "en": "flu"},
        {"fi": "kuume", "en": "fever"},
        {"fi": "yskä", "en": "cough"},
        {"fi": "tabletti", "en": "tablet/pill"},
        {"fi": "resepti", "en": "prescription"},
        {"fi": "tarkastus", "en": "check-up"},
        {"fi": "Minulla on flunssa.", "en": "I have the flu."},
        {"fi": "Tarvitsen lääkärin ajan.", "en": "I need a doctor’s appointment."},
        {"fi": "Missä on lähin apteekki?", "en": "Where is the nearest pharmacy?"},
        {"fi": "Onko sinulla kuumetta?", "en": "Do you have a fever?"},
        {"fi": "Sain reseptin lääkäriltä.", "en": "I got a prescription from the doctor."},
        {"fi": "Milloin tarkastus on?", "en": "When is the check-up?"},
        {"fi": "Olen allerginen pähkinöille.", "en": "I'm allergic to nuts."},
        {"fi": "Missä on ensiapu?", "en": "Where is the first aid?"},
        {"fi": "Voitko soittaa lääkärille?", "en": "Can you call a doctor?"},
        {"fi": "Tunnen oloni huonoksi.", "en": "I feel unwell."},
    ],
    "Family": [
        {"fi": "perhe", "en": "family"},
        {"fi": "äiti", "en": "mother"},
        {"fi": "isä", "en": "father"},
        {"fi": "veli", "en": "brother"},
        {"fi": "sisko", "en": "sister"},
        {"fi": "lapsi", "en": "child"},
        {"fi": "vaimo", "en": "wife"},
        {"fi": "mies", "en": "husband"},
        {"fi": "isovanhemmat", "en": "grandparents"},
        {"fi": "serkku", "en": "cousin"},
        {"fi": "Minulla on iso perhe.", "en": "I have a big family."},
        {"fi": "Äitini nimi on Anna.", "en": "My mother’s name is Anna."},
        {"fi": "Minulla on yksi veli ja kaksi siskoa.", "en": "I have one brother and two sisters."},
        {"fi": "Isoäitini asuu Tampereella.", "en": "My grandmother lives in Tampere."},
        {"fi": "Vaimoni puhuu suomea ja englantia.", "en": "My wife speaks Finnish and English."},
        {"fi": "Serkkuni tulee vierailulle.", "en": "My cousin is coming to visit."},
        {"fi": "Oletko naimisissa?", "en": "Are you married?"},
        {"fi": "Minulla on kolme lasta.", "en": "I have three children."},
        {"fi": "Tämä on ystäväni.", "en": "This is my friend."},
    ],
    "Nature & Outdoors": [
        {"fi": "metsä", "en": "forest"},
        {"fi": "järvi", "en": "lake"},
        {"fi": "joki", "en": "river"},
        {"fi": "vuori", "en": "mountain"},
        {"fi": "polku", "en": "trail/path"},
        {"fi": "teltta", "en": "tent"},
        {"fi": "nuotio", "en": "campfire"},
        {"fi": "lintu", "en": "bird"},
        {"fi": "kukka", "en": "flower"},
        {"fi": "aurinko", "en": "sun"},
        {"fi": "Mennään metsään kävelylle.", "en": "Let’s go for a walk in the forest."},
        {"fi": "Näin järvellä joutsenen.", "en": "I saw a swan at the lake."},
        {"fi": "Rakennamme teltan tänne.", "en": "We will set up the tent here."},
        {"fi": "Nuotio lämmittää mukavasti.", "en": "The campfire is pleasantly warm."},
        {"fi": "Aurinko paistaa kirkkaasti.", "en": "The sun is shining brightly."},
        {"fi": "Missä polku alkaa?", "en": "Where does the trail begin?"},
        {"fi": "Uin järvessä kesäisin.", "en": "I swim in the lake in summer."},
        {"fi": "Metsässä on rauhallista.", "en": "It's peaceful in the forest."},
        {"fi": "Pidätkö retkeilystä?", "en": "Do you like hiking?"},
        {"fi": "Otan kuvia luonnosta.", "en": "I take pictures of nature."},
    ],

    "Transportation": [
        {"fi": "auto", "en": "car"},
        {"fi": "bussi", "en": "bus"},
        {"fi": "juna", "en": "train"},
        {"fi": "metro", "en": "metro/subway"},
        {"fi": "raitiovaunu", "en": "tram"},
        {"fi": "pysäkki", "en": "stop (e.g. bus stop)"},
        {"fi": "lippu", "en": "ticket"},
        {"fi": "kuljettaja", "en": "driver"},
        {"fi": "nopeus", "en": "speed"},
        {"fi": "kartta", "en": "map"},
        {"fi": "Missä on lähin bussipysäkki?", "en": "Where is the nearest bus stop?"},
        {"fi": "Tarvitsen lipun Helsinkiin.", "en": "I need a ticket to Helsinki."},
        {"fi": "Juna lähtee kello kahdeksan.", "en": "The train leaves at eight o’clock."},
        {"fi": "Aja varovasti!", "en": "Drive carefully!"},
        {"fi": "Voitko näyttää kartan?", "en": "Can you show the map?"},
        {"fi": "Kuljettaja pysäytti auton.", "en": "The driver stopped the car."},
        {"fi": "Onko tämä oikea bussi keskustaan?", "en": "Is this the right bus to the city center?"},
        {"fi": "Milloin seuraava juna lähtee?", "en": "When does the next train leave?"},
        {"fi": "Mihin tämä bussi menee?", "en": "Where does this bus go?"},
        {"fi": "Kuinka paljon matka maksaa?", "en": "How much does the trip cost?"},
        {"fi": "Pääseekö täältä lentokentälle?", "en": "Can I get to the airport from here?"},
        {"fi": "Tarvitsen aikataulun.", "en": "I need a timetable."},
        {"fi": "Missä on taksitolppa?", "en": "Where is the taxi stand?"},
        {"fi": "Saanko kyydin asemalle?", "en": "Can I get a ride to the station?"},
        {"fi": "Matka kestää noin 20 minuuttia.", "en": "The journey takes about 20 minutes."},
        {"fi": "Odota tässä pysäkillä.", "en": "Wait at this stop."},
        {"fi": "Jään pois seuraavalla pysäkillä.", "en": "I get off at the next stop."},
    ],
    "School & Learning": [
        {"fi": "koulu", "en": "school"},
        {"fi": "oppilas", "en": "student"},
        {"fi": "opettaja", "en": "teacher"},
        {"fi": "luokka", "en": "classroom"},
        {"fi": "kirja", "en": "book"},
        {"fi": "vihko", "en": "notebook"},
        {"fi": "kynä", "en": "pen"},
        {"fi": "koe", "en": "test"},
        {"fi": "läksyt", "en": "homework"},
        {"fi": "kurssi", "en": "course"},
        {"fi": "Menen kouluun kahdeksalta.", "en": "I go to school at eight."},
        {"fi": "Opettaja selittää hyvin.", "en": "The teacher explains well."},
        {"fi": "Missä luokka on?", "en": "Where is the classroom?"},
        {"fi": "Tarvitsen uuden vihkon.", "en": "I need a new notebook."},
        {"fi": "Koe oli vaikea.", "en": "The test was hard."},
        {"fi": "Teen läksyt illalla.", "en": "I do my homework in the evening."},
        {"fi": "Pidän matematiikasta.", "en": "I like mathematics."},
        {"fi": "Onko sinulla kynää?", "en": "Do you have a pen?"},
        {"fi": "Opiskelen englantia.", "en": "I study English."},
        {"fi": "Missä kirjasto on?", "en": "Where is the library?"},
        {"fi": "Kurssi alkaa huomenna.", "en": "The course starts tomorrow."},
        {"fi": "Tarvitsen apua tehtävän kanssa.", "en": "I need help with the assignment."},
        {"fi": "Luen kokeeseen.", "en": "I am studying for a test."},
        {"fi": "Onko sinulla muistiinpanot mukana?", "en": "Do you have the notes with you?"},
        {"fi": "Voitko lainata kirjaa?", "en": "Can you lend the book?"},
    ],
    "Numbers & Time": [
        {"fi": "yksi", "en": "one"},
        {"fi": "kaksi", "en": "two"},
        {"fi": "kolme", "en": "three"},
        {"fi": "neljä", "en": "four"},
        {"fi": "viisi", "en": "five"},
        {"fi": "kuusi", "en": "six"},
        {"fi": "seitsemän", "en": "seven"},
        {"fi": "kahdeksan", "en": "eight"},
        {"fi": "yhdeksän", "en": "nine"},
        {"fi": "kymmenen", "en": "ten"},
        {"fi": "tunti", "en": "hour"},
        {"fi": "minuutti", "en": "minute"},
        {"fi": "sekunti", "en": "second"},
        {"fi": "päivä", "en": "day"},
        {"fi": "viikko", "en": "week"},
        {"fi": "kuukausi", "en": "month"},
        {"fi": "vuosi", "en": "year"},
        {"fi": "Mikä päivä tänään on?", "en": "What day is it today?"},
        {"fi": "Kello on kolme.", "en": "It is three o'clock."},
        {"fi": "Kuinka monta tuntia?", "en": "How many hours?"},
        {"fi": "Tänään on maanantai.", "en": "Today is Monday."},
        {"fi": "Kuinka vanha olet?", "en": "How old are you?"},
        {"fi": "Aloitamme kello yhdeksän.", "en": "We start at nine o'clock."},
        {"fi": "Paljonko kello on?", "en": "What time is it?"},
        {"fi": "Viikonloppu alkaa perjantaina.", "en": "The weekend starts on Friday."},
    ],   

    "Colors & Shapes": [
        {"fi": "punainen", "en": "red"},
        {"fi": "sininen", "en": "blue"},
        {"fi": "vihreä", "en": "green"},
        {"fi": "keltainen", "en": "yellow"},
        {"fi": "musta", "en": "black"},
        {"fi": "valkoinen", "en": "white"},
        {"fi": "harmaa", "en": "grey"},
        {"fi": "ruskea", "en": "brown"},
        {"fi": "oranssi", "en": "orange"},
        {"fi": "vaaleanpunainen", "en": "pink"},
        {"fi": "ympyrä", "en": "circle"},
        {"fi": "neliö", "en": "square"},
        {"fi": "kolmio", "en": "triangle"},
        {"fi": "suorakulmio", "en": "rectangle"},
        {"fi": "soikio", "en": "oval"},
        {"fi": "tähti", "en": "star"},
        {"fi": "Minkä värinen tämä on?", "en": "What color is this?"},
        {"fi": "Se on punainen neliö.", "en": "It's a red square."},
        {"fi": "Pidätkö sinisestä?", "en": "Do you like blue?"},
        {"fi": "Nämä kukat ovat keltaisia.", "en": "These flowers are yellow."},
        {"fi": "Talossa on harmaa katto.", "en": "The house has a grey roof."},
        {"fi": "Voitko piirtää kolmion?", "en": "Can you draw a triangle?"},
        {"fi": "Minulla on valkoinen auto.", "en": "I have a white car."},
        {"fi": "Lippu on sininen ja valkoinen.", "en": "The flag is blue and white."},
    ],
    "Body & Health": [
        {"fi": "pää", "en": "head"},
        {"fi": "silmä", "en": "eye"},
        {"fi": "korva", "en": "ear"},
        {"fi": "nenä", "en": "nose"},
        {"fi": "suu", "en": "mouth"},
        {"fi": "hammas", "en": "tooth"},
        {"fi": "käsi", "en": "hand"},
        {"fi": "jalka", "en": "leg/foot"},
        {"fi": "sormi", "en": "finger"},
        {"fi": "varvas", "en": "toe"},
        {"fi": "vatsa", "en": "stomach"},
        {"fi": "selkä", "en": "back"},
        {"fi": "Mihin sattuu?", "en": "Where does it hurt?"},
        {"fi": "Minulla on päänsärky.", "en": "I have a headache."},
        {"fi": "Voitko hengittää syvään?", "en": "Can you breathe deeply?"},
        {"fi": "Ota lääkettä kerran päivässä.", "en": "Take medicine once a day."},
        {"fi": "Oletko allerginen jollekin?", "en": "Are you allergic to anything?"},
        {"fi": "Haluan varata ajan lääkärille.", "en": "I want to make a doctor's appointment."},
        {"fi": "Minulla on vatsakipua.", "en": "I have a stomach ache."},
        {"fi": "Tarvitsen laastarin.", "en": "I need a bandage."},
        {"fi": "Minulla on kuumetta.", "en": "I have a fever."},
        {"fi": "Tarkista verenpaineesi.", "en": "Check your blood pressure."},
        {"fi": "Käytä hammasharjaa päivittäin.", "en": "Use a toothbrush daily."},
        {"fi": "Muista pestä kädet.", "en": "Remember to wash your hands."},
    ],
    "Directions & Places": [
        {"fi": "oikea", "en": "right"},
        {"fi": "vasen", "en": "left"},
        {"fi": "suora", "en": "straight"},
        {"fi": "takana", "en": "behind"},
        {"fi": "edessä", "en": "in front of"},
        {"fi": "ylhäällä", "en": "up"},
        {"fi": "alhaalla", "en": "down"},
        {"fi": "kaupungintalo", "en": "city hall"},
        {"fi": "kirjasto", "en": "library"},
        {"fi": "teatteri", "en": "theater"},
        {"fi": "puisto", "en": "park"},
        {"fi": "kauppakeskus", "en": "shopping center"},
        {"fi": "ravintola", "en": "restaurant"},
        {"fi": "pankki", "en": "bank"},
        {"fi": "apteekki", "en": "pharmacy"},
        {"fi": "Missä on lähin kirjasto?", "en": "Where is the nearest library?"},
        {"fi": "Miten pääsen puistoon?", "en": "How do I get to the park?"},
        {"fi": "Käänny oikealle seuraavasta risteyksestä.", "en": "Turn right at the next intersection."},
        {"fi": "Ravintola on vasemmalla.", "en": "The restaurant is on the left."},
        {"fi": "Mene suoraan eteenpäin.", "en": "Go straight ahead."},
        {"fi": "Kaupungintalo on edessä.", "en": "The city hall is in front."},
        {"fi": "Pankki on kauppakeskuksen takana.", "en": "The bank is behind the shopping center."},
        {"fi": "Apteekki on ylhäällä toisessa kerroksessa.", "en": "The pharmacy is upstairs on the second floor."},
    ],    
    
    "Common Verbs & Questions": [
        {"fi": "mennä", "en": "to go"},
        {"fi": "tulla", "en": "to come"},
        {"fi": "tehdä", "en": "to do/make"},
        {"fi": "nähdä", "en": "to see"},
        {"fi": "kuulla", "en": "to hear"},
        {"fi": "puhua", "en": "to speak"},
        {"fi": "syödä", "en": "to eat"},
        {"fi": "juoda", "en": "to drink"},
        {"fi": "asua", "en": "to live"},
        {"fi": "rakastaa", "en": "to love"},
        {"fi": "tykätä", "en": "to like"},
        {"fi": "haluta", "en": "to want"},
        {"fi": "tarvita", "en": "to need"},
        {"fi": "Saanko auttaa?", "en": "May I help?"},
        {"fi": "Voitko toistaa?", "en": "Can you repeat?"},
        {"fi": "Miten sanotaan suomeksi?", "en": "How do you say it in Finnish?"},
        {"fi": "Missä asut?", "en": "Where do you live?"},
        {"fi": "Mitä teet työksesi?", "en": "What do you do for a living?"},
        {"fi": "Rakastan suomen kieltä.", "en": "I love the Finnish language."},
        {"fi": "Mitä aiot tehdä huomenna?", "en": "What are you going to do tomorrow?"},
        {"fi": "Voinko kysyä jotain?", "en": "Can I ask something?"},
        {"fi": "Osaatko puhua suomea?", "en": "Can you speak Finnish?"},
        {"fi": "Kuka tämä on?", "en": "Who is this?"},
        {"fi": "Milloin lähdet?", "en": "When do you leave?"},
        {"fi": "Miksi olet myöhässä?", "en": "Why are you late?"},
        {"fi": "Miten menee?", "en": "How is it going?"},
        {"fi": "Mistä tulet?", "en": "Where are you from?"},
        {"fi": "Kuinka vanha olet?", "en": "How old are you?"},
        {"fi": "Mitä haluat syödä?", "en": "What do you want to eat?"},
        {"fi": "Mihin aikaan kokous alkaa?", "en": "What time does the meeting start?"},
        {"fi": "Voitko auttaa minua?", "en": "Can you help me?"},
        {"fi": "Tarvitsetko apua?", "en": "Do you need help?"},
    ],
    "Animals & Nature": [
        {"fi": "koira", "en": "dog"},
        {"fi": "kissa", "en": "cat"},
        {"fi": "hevonen", "en": "horse"},
        {"fi": "lehmä", "en": "cow"},
        {"fi": "sika", "en": "pig"},
        {"fi": "lammas", "en": "sheep"},
        {"fi": "kani", "en": "rabbit"},
        {"fi": "kana", "en": "chicken"},
        {"fi": "kala", "en": "fish"},
        {"fi": "lintu", "en": "bird"},
        {"fi": "puu", "en": "tree"},
        {"fi": "heinä", "en": "grass"},
        {"fi": "meri", "en": "sea"},
        {"fi": "saari", "en": "island"},
        {"fi": "auringonnousu", "en": "sunrise"},
        {"fi": "auringonlasku", "en": "sunset"},
        {"fi": "karhu", "en": "bear"},
        {"fi": "susi", "en": "wolf"},
        {"fi": "hirvi", "en": "elk/moose"},
        {"fi": "kettu", "en": "fox"},
        {"fi": "orava", "en": "squirrel"},
        {"fi": "metsä", "en": "forest"},
        {"fi": "järvi", "en": "lake"},
        {"fi": "joki", "en": "river"},
        {"fi": "vuori", "en": "mountain"},
        {"fi": "kukka", "en": "flower"},
        {"fi": "Onko sinulla lemmikkiä?", "en": "Do you have a pet?"},
        {"fi": "Meri on sininen.", "en": "The sea is blue."},
        {"fi": "Kissat ovat söpöjä.", "en": "Cats are cute."},
        {"fi": "Oravat juoksevat puussa.", "en": "Squirrels run in the tree."},
        {"fi": "Karhu nukkuu talvella.", "en": "The bear sleeps in winter."},
        {"fi": "Näin järvellä joutsenen.", "en": "I saw a swan at the lake."},
        {"fi": "Rakastan luontoa.", "en": "I love nature."},
        {"fi": "Kesällä aurinko ei laske.", "en": "The sun doesn't set in summer."},
    ],
    "Technology & Media": [
        {"fi": "puhelin", "en": "phone"},
        {"fi": "tietokone", "en": "computer"},
        {"fi": "televisio", "en": "television"},
        {"fi": "kamera", "en": "camera"},
        {"fi": "kuulokkeet", "en": "headphones"},
        {"fi": "hiiri", "en": "mouse (device)"},
        {"fi": "näyttö", "en": "screen"},
        {"fi": "internet", "en": "internet"},
        {"fi": "laturi", "en": "charger"},
        {"fi": "sovellus", "en": "app"},
        {"fi": "wifi", "en": "wifi"},
        {"fi": "tulostin", "en": "printer"},
        {"fi": "kaiutin", "en": "speaker"},
        {"fi": "verkkoyhteys", "en": "network connection"},
        {"fi": "sähköposti", "en": "email"},
        {"fi": "verkkosivu", "en": "website"},
        {"fi": "tabletti", "en": "tablet (device)"},
        {"fi": "soitin", "en": "player (media)"},
        {"fi": "Ohjelma ei toimi.", "en": "The program does not work."},
        {"fi": "Onko täällä wifiä?", "en": "Is there wifi here?"},
        {"fi": "Puhelimeni on rikki.", "en": "My phone is broken."},
        {"fi": "Tarvitsen laturin.", "en": "I need a charger."},
        {"fi": "Missä on tietokonehuone?", "en": "Where is the computer room?"},
        {"fi": "Käytän tätä sovellusta.", "en": "I use this app."},
        {"fi": "Voitko lähettää sähköpostin?", "en": "Can you send an email?"},
        {"fi": "Katson elokuvia tabletilla.", "en": "I watch movies on the tablet."},
        {"fi": "Tulostin on tyhjä.", "en": "The printer is empty."},
        {"fi": "Kirjoitan blogia internetissä.", "en": "I write a blog on the internet."},
        {"fi": "Voinko lainata kuulokkeita?", "en": "Can I borrow headphones?"},
        {"fi": "Lähetän viestin puhelimella.", "en": "I send a message with my phone."},
        {"fi": "Kytke laite verkkovirtaan.", "en": "Connect the device to the mains."},
        {"fi": "Osta uusi näyttö.", "en": "Buy a new screen."},
    ],
    
    "Shopping & Money": [
        {"fi": "kauppa", "en": "shop"},
        {"fi": "hinta", "en": "price"},
        {"fi": "raha", "en": "money"},
        {"fi": "alennus", "en": "discount"},
        {"fi": "lasku", "en": "bill"},
        {"fi": "kuitti", "en": "receipt"},
        {"fi": "pankkikortti", "en": "bank card"},
        {"fi": "käteinen", "en": "cash"},
        {"fi": "ostoskori", "en": "shopping basket"},
        {"fi": "ostoskärry", "en": "shopping cart"},
        {"fi": "Onko tämä tarjouksessa?", "en": "Is this on sale?"},
        {"fi": "Missä on kassa?", "en": "Where is the checkout?"},
        {"fi": "Voinko maksaa käteisellä?", "en": "Can I pay in cash?"},
        {"fi": "Tarvitsen kuitin.", "en": "I need a receipt."},
        {"fi": "Paljon tämä maksaa?", "en": "How much does this cost?"},
        {"fi": "Haluan palauttaa tämän.", "en": "I want to return this."},
        {"fi": "Onko teillä vaihtorahaa?", "en": "Do you have change?"},
        {"fi": "Ostan tämän kortilla.", "en": "I buy this with a card."},
        {"fi": "Saisinko alennuksen?", "en": "Could I get a discount?"},
        {"fi": "Voitteko pakata tämän?", "en": "Can you pack this?"},
        {"fi": "Voinko maksaa osamaksulla?", "en": "Can I pay in installments?"},
        {"fi": "Kassalla on jono.", "en": "There is a queue at the checkout."},
        {"fi": "Etsin lahjaa ystävälleni.", "en": "I'm looking for a gift for my friend."},
        {"fi": "Tarvitsetko ostoskassin?", "en": "Do you need a shopping bag?"},
        {"fi": "Voinko palauttaa tämän ilman kuittia?", "en": "Can I return this without a receipt?"},
        {"fi": "Tämä on liian kallis.", "en": "This is too expensive."},
        {"fi": "Onko teillä tätä halvemmalla?", "en": "Do you have this cheaper?"},
        {"fi": "Saan alennusta opiskelijana.", "en": "I get a discount as a student."},
    ],
    "Family & Relationships": [
        {"fi": "poika", "en": "son"},
        {"fi": "tytär", "en": "daughter"},
        {"fi": "lapsenlapsi", "en": "grandchild"},
        {"fi": "setä", "en": "uncle"},
        {"fi": "täti", "en": "aunt"},
        {"fi": "eno", "en": "maternal uncle"},
        {"fi": "apu", "en": "help"},
        {"fi": "ystävä", "en": "friend"},
        {"fi": "ystävätär", "en": "female friend"},
        {"fi": "naapuri", "en": "neighbor"},
        {"fi": "Oletko naimisissa?", "en": "Are you married?"},
        {"fi": "Minulla on kolme lasta.", "en": "I have three children."},
        {"fi": "Tämä on ystäväni.", "en": "This is my friend."},
        {"fi": "Naapurini on mukava.", "en": "My neighbor is nice."},
        {"fi": "Isäni työskentelee lääkärinä.", "en": "My father works as a doctor."},
        {"fi": "Setäni asuu Helsingissä.", "en": "My uncle lives in Helsinki."},
        {"fi": "Olemme olleet ystäviä pitkään.", "en": "We have been friends for a long time."},
        {"fi": "Rakastan perhettäni.", "en": "I love my family."},
        {"fi": "Tapaan sukulaiset viikonloppuna.", "en": "I will meet relatives on the weekend."},
        {"fi": "Vaimoni pitää musiikista.", "en": "My wife likes music."},
        {"fi": "Veljeni on nuorempi kuin minä.", "en": "My brother is younger than me."},
        {"fi": "Meillä on suuri suku.", "en": "We have a big extended family."},
        {"fi": "Minulla ei ole sisaruksia.", "en": "I have no siblings."},
        {"fi": "Isoisäni harrastaa kalastusta.", "en": "My grandfather is into fishing."},
        {"fi": "Kenen kanssa asut?", "en": "Who do you live with?"},
        {"fi": "Pidämme yhteyttä usein.", "en": "We keep in touch often."},
        {"fi": "Vanhempani asuvat ulkomailla.", "en": "My parents live abroad."},
        {"fi": "Olen kihloissa.", "en": "I am engaged."},
        {"fi": "Serkkuni on paras ystäväni.", "en": "My cousin is my best friend."},
    ],
    "Leisure & Activities": [
        {"fi": "elokuva", "en": "movie"},
        {"fi": "kirja", "en": "book"},
        {"fi": "musiikki", "en": "music"},
        {"fi": "urheilu", "en": "sport"},
        {"fi": "tanssi", "en": "dance"},
        {"fi": "piirtäminen", "en": "drawing"},
        {"fi": "valokuvaus", "en": "photography"},
        {"fi": "kalastus", "en": "fishing"},
        {"fi": "retkeily", "en": "hiking"},
        {"fi": "uinti", "en": "swimming"},
        {"fi": "Käydään elokuvissa.", "en": "Let's go to the movies."},
        {"fi": "Luetko paljon kirjoja?", "en": "Do you read a lot of books?"},
        {"fi": "Pidätkö musiikista?", "en": "Do you like music?"},
        {"fi": "Harrastan uintia.", "en": "I do swimming as a hobby."},
        {"fi": "Rakastan tanssia.", "en": "I love dancing."},
        {"fi": "Kalastus on hauskaa.", "en": "Fishing is fun."},
        {"fi": "Soitan kitaraa vapaa-ajalla.", "en": "I play guitar in my free time."},
        {"fi": "Uin järvessä kesäisin.", "en": "I swim in the lake in summer."},
        {"fi": "Juoksen usein puistossa.", "en": "I often run in the park."},
        {"fi": "Osallistun maalauskurssille.", "en": "I attend a painting class."},
        {"fi": "Käymme kävelyllä iltaisin.", "en": "We go for a walk in the evenings."},
        {"fi": "Harrastan valokuvausta.", "en": "My hobby is photography."},
        {"fi": "Pelaamme lautapelejä perheen kanssa.", "en": "We play board games with the family."},
        {"fi": "Aion oppia tanssimaan.", "en": "I plan to learn to dance."},
        {"fi": "Käyn kuntosalilla kolme kertaa viikossa.", "en": "I go to the gym three times a week."},
        {"fi": "Katsomme elokuvia viikonloppuisin.", "en": "We watch movies on weekends."},
        {"fi": "Piirrän mielelläni.", "en": "I like drawing."},
        {"fi": "Osaatko pelata shakkia?", "en": "Can you play chess?"},
        {"fi": "Järjestämme juhlia ystäville.", "en": "We organize parties for friends."},
        {"fi": "Käyn konserteissa.", "en": "I go to concerts."},
    ],    

    "Daily routines": [
        {"fi": "Herään seitsemältä aamulla.", "en": "I wake up at seven in the morning."},
        {"fi": "Menen töihin bussilla.", "en": "I go to work by bus."},
        {"fi": "Syön aamiaista kotona.", "en": "I eat breakfast at home."},
        {"fi": "Luen uutisia puhelimella.", "en": "I read news on my phone."},
        {"fi": "Lähden kotiin kello viisi.", "en": "I leave for home at five o'clock."},
        {"fi": "Menemme nukkumaan aikaisin.", "en": "We go to bed early."},
        {"fi": "Juon kupin teetä iltaisin.", "en": "I drink a cup of tea in the evenings."},
        {"fi": "Teen töitä etänä.", "en": "I work remotely."},
        {"fi": "Tulen takaisin myöhemmin.", "en": "I will come back later."},
        {"fi": "Otan päivän rennosti.", "en": "I take it easy today."},
        {"fi": "Käyn suihkussa joka aamu.", "en": "I take a shower every morning."},
        {"fi": "Vien roskat ulos.", "en": "I take out the trash."},
        {"fi": "Käyn kaupassa iltapäivällä.", "en": "I go shopping in the afternoon."},
        {"fi": "Teen ruokaa itse.", "en": "I cook food myself."},
        {"fi": "Siivoan keittiön illalla.", "en": "I clean the kitchen in the evening."},
        {"fi": "Kastelen kukat viikoittain.", "en": "I water the flowers weekly."},
        {"fi": "Soitan ystävälle töiden jälkeen.", "en": "I call a friend after work."},
        {"fi": "Katselen televisiota hetken.", "en": "I watch television for a while."},
        {"fi": "Pesen hampaat kahdesti päivässä.", "en": "I brush my teeth twice a day."},
        {"fi": "Valmistan eväät seuraavalle päivälle.", "en": "I prepare snacks for the next day."},
    ],
    "At the store/market": [
        {"fi": "Voinko saada apua?", "en": "Can I get some help?"},
        {"fi": "Etsin tätä tuotetta.", "en": "I'm looking for this product."},
        {"fi": "Onko teillä tarjouksia tänään?", "en": "Do you have any offers today?"},
        {"fi": "Voinko palauttaa tämän tuotteen?", "en": "Can I return this product?"},
        {"fi": "Tarvitsen toisen koon.", "en": "I need a different size."},
        {"fi": "Voitteko pakata tämän lahjaksi?", "en": "Can you wrap this as a gift?"},
        {"fi": "Missä sovituskopit ovat?", "en": "Where are the fitting rooms?"},
        {"fi": "Haluaisin ostaa tämän.", "en": "I would like to buy this."},
        {"fi": "Voinko maksaa mobiililla?", "en": "Can I pay by mobile?"},
        {"fi": "Saisinko kuitin, kiitos.", "en": "Could I have a receipt, please?"},
        {"fi": "Paljon tämä maksaa?", "en": "How much does this cost?"},
        {"fi": "Onko tuotteella takuu?", "en": "Does the product have a warranty?"},
        {"fi": "Voinko vaihtaa tämän?", "en": "Can I exchange this?"},
        {"fi": "Missä on lähin apteekki?", "en": "Where is the nearest pharmacy?"},
        {"fi": "Tarvitsen ostoslistan.", "en": "I need a shopping list."},
        {"fi": "Voitteko auttaa etsimään tämän?", "en": "Can you help me find this?"},
        {"fi": "Haluan palauttaa ostokseni.", "en": "I want to return my purchase."},
        {"fi": "Onko tämä tuote tuore?", "en": "Is this product fresh?"},
        {"fi": "Voinko maksaa kortilla?", "en": "Can I pay by card?"},
        {"fi": "Missä on vihannesosasto?", "en": "Where is the vegetable section?"},
    ],
    "At the restaurant": [
        {"fi": "Onko teillä kasvisvaihtoehtoja?", "en": "Do you have vegetarian options?"},
        {"fi": "Voinko saada ruokalistan?", "en": "Can I have the menu?"},
        {"fi": "Mikä on päivän annos?", "en": "What is the dish of the day?"},
        {"fi": "Odotamme vielä yhtä henkilöä.", "en": "We are still waiting for one person."},
        {"fi": "Voitteko suositella jotain?", "en": "Can you recommend something?"},
        {"fi": "Voinko saada veden ilman jääpaloja?", "en": "Can I have water without ice?"},
        {"fi": "Oliko kaikki kunnossa?", "en": "Was everything alright?"},
        {"fi": "Voinko maksaa laskun erikseen?", "en": "Can I pay the bill separately?"},
        {"fi": "Ruoka oli herkullista.", "en": "The food was delicious."},
        {"fi": "Kiitos ja hyvää päivänjatkoa!", "en": "Thank you and have a nice day!"},
        {"fi": "Onko pöytä varattu?", "en": "Is the table reserved?"},
        {"fi": "Saanko lasten annoksen?", "en": "Can I have a kid's meal?"},
        {"fi": "Tarvitsemme lisää lautasia.", "en": "We need more plates."},
        {"fi": "Voinko tilata jälkiruoan?", "en": "Can I order dessert?"},
        {"fi": "Missä on wc?", "en": "Where is the restroom?"},
        {"fi": "Saanko laskun, kiitos.", "en": "Can I get the bill, please?"},
        {"fi": "Voinko maksaa käteisellä?", "en": "Can I pay in cash?"},
        {"fi": "Onko palvelumaksu mukana?", "en": "Is the service charge included?"},
        {"fi": "Kuinka kauan ruoan saaminen kestää?", "en": "How long does it take to get the food?"},
        {"fi": "Voinko vaihtaa pöytää?", "en": "Can I change tables?"},
    ],    

    "Emergencies & Health": [
        {"fi": "Soita ambulanssi!", "en": "Call an ambulance!"},
        {"fi": "Tarvitsen apua nopeasti.", "en": "I need help quickly."},
        {"fi": "Olen allerginen pähkinöille.", "en": "I'm allergic to nuts."},
        {"fi": "Missä on ensiapu?", "en": "Where is the first aid?"},
        {"fi": "Tunnen oloni huonoksi.", "en": "I feel unwell."},
        {"fi": "Voitko soittaa lääkärille?", "en": "Can you call a doctor?"},
        {"fi": "Tarvitsen lääkettä apteekista.", "en": "I need medicine from the pharmacy."},
        {"fi": "Voitko auttaa minua löytämään lääkkeen?", "en": "Can you help me find the medicine?"},
        {"fi": "Olen loukannut jalkani.", "en": "I have injured my leg."},
        {"fi": "Tarvitsen tulkin.", "en": "I need an interpreter."},
        {"fi": "Onko sinulla sairausvakuutusta?", "en": "Do you have health insurance?"},
        {"fi": "Missä on lähin sairaala?", "en": "Where is the nearest hospital?"},
        {"fi": "Minulla on hengitysvaikeuksia.", "en": "I have difficulty breathing."},
        {"fi": "Onko sinulla astmaa?", "en": "Do you have asthma?"},
        {"fi": "Ota tämä lääke kahdesti päivässä.", "en": "Take this medicine twice a day."},
        {"fi": "Onko sinulla veriryhmätietoja?", "en": "Do you know your blood type?"},
        {"fi": "Olen saanut palovamman.", "en": "I have a burn injury."},
        {"fi": "Voitko auttaa minua istumaan?", "en": "Can you help me to sit down?"},
        {"fi": "Tarvitsen kylmäpakkauksen.", "en": "I need an ice pack."},
        {"fi": "Missä on lähin apteekki?", "en": "Where is the nearest pharmacy?"},
    ],
    "Feelings & reactions": [
        {"fi": "Olen erittäin iloinen tästä.", "en": "I am very happy about this."},
        {"fi": "Se kuulostaa hyvältä.", "en": "That sounds good."},
        {"fi": "Olen pettynyt tulokseen.", "en": "I am disappointed with the result."},
        {"fi": "En ole varma tästä.", "en": "I'm not sure about this."},
        {"fi": "Toivottavasti onnistut.", "en": "I hope you succeed."},
        {"fi": "Onpa harmi kuulla.", "en": "That's a pity to hear."},
        {"fi": "Olen hieman hermostunut.", "en": "I am a bit nervous."},
        {"fi": "Olen ylpeä saavutuksestasi.", "en": "I am proud of your achievement."},
        {"fi": "Voin auttaa sinua tarvittaessa.", "en": "I can help you if needed."},
        {"fi": "Tämä tekee minut onnelliseksi.", "en": "This makes me happy."},
        {"fi": "Olen todella kiitollinen avustasi.", "en": "I'm really grateful for your help."},
        {"fi": "Anteeksi, se oli minun syyni.", "en": "Sorry, that was my fault."},
        {"fi": "Olen hämmästynyt tästä uutisesta.", "en": "I'm amazed by this news."},
        {"fi": "Se on minulle tärkeää.", "en": "That is important to me."},
        {"fi": "Olen huolissani sinusta.", "en": "I'm worried about you."},
        {"fi": "Olen vihainen tästä tilanteesta.", "en": "I'm angry about this situation."},
        {"fi": "Pidän tästä ideasta.", "en": "I like this idea."},
        {"fi": "Toivon parasta.", "en": "I wish for the best."},
        {"fi": "Olen innoissani tulevasta.", "en": "I'm excited for the future."},
        {"fi": "Olet rohkea.", "en": "You are brave."},
    ],
    "At the office/school": [
        {"fi": "Voitko tulostaa tämän asiakirjan?", "en": "Can you print this document?"},
        {"fi": "Tarvitsen apua tehtävän kanssa.", "en": "I need help with the assignment."},
        {"fi": "Voimmeko pitää kokouksen huomenna?", "en": "Can we have the meeting tomorrow?"},
        {"fi": "Onko sinulla muistiinpanot mukana?", "en": "Do you have the notes with you?"},
        {"fi": "Lähetän raportin tänään.", "en": "I'll send the report today."},
        {"fi": "Kokeen tulokset julkaistaan ensi viikolla.", "en": "The test results will be published next week."},
        {"fi": "Missä on luokkahuone numero viisi?", "en": "Where is classroom number five?"},
        {"fi": "Opettaja selittää asian uudelleen.", "en": "The teacher explains the matter again."},
        {"fi": "Tauko alkaa nyt.", "en": "The break starts now."},
        {"fi": "Projektin deadline lähestyy.", "en": "The project deadline is approaching."},
        {"fi": "Kirjoita nimesi tähän.", "en": "Write your name here."},
        {"fi": "Missä voin kopioida asiakirjoja?", "en": "Where can I copy documents?"},
        {"fi": "Tarvitsen uuden vihkon.", "en": "I need a new notebook."},
        {"fi": "Voitko lähettää sähköpostin?", "en": "Can you send an email?"},
        {"fi": "Käytätkö tietokonetta tunnilla?", "en": "Do you use a computer in class?"},
        {"fi": "Lukujärjestys vaihtuu ensi kuussa.", "en": "The timetable changes next month."},
        {"fi": "Missä pidetään seuraava kokous?", "en": "Where is the next meeting held?"},
        {"fi": "Voitko avata ikkunan?", "en": "Can you open the window?"},
        {"fi": "Tarvitsen lisää aikaa tehtävään.", "en": "I need more time for the assignment."},
        {"fi": "Onko sinulla kysyttävää?", "en": "Do you have any questions?"},
    ],

    "Home & family": [
        {"fi": "Asumme kolmikerroksisessa talossa.", "en": "We live in a three-story house."},
        {"fi": "Lapset leikkivät pihalla.", "en": "The children are playing in the yard."},
        {"fi": "Keittiössä on paljon valoa.", "en": "There is a lot of light in the kitchen."},
        {"fi": "Perheeni tulee vierailulle viikonloppuna.", "en": "My family is coming to visit this weekend."},
        {"fi": "Pesen pyykkiä joka lauantai.", "en": "I do laundry every Saturday."},
        {"fi": "Tarvitsemme lisää ruokaa jääkaappiin.", "en": "We need more food in the fridge."},
        {"fi": "Olen kotona iltaan asti.", "en": "I'll be home until the evening."},
        {"fi": "Vietämme aikaa yhdessä iltaisin.", "en": "We spend time together in the evenings."},
        {"fi": "Tänään on siivouspäivä.", "en": "Today is cleaning day."},
        {"fi": "Naapuri auttaa meitä usein.", "en": "The neighbor often helps us."},
        {"fi": "Minun veljeni käy koulua.", "en": "My brother goes to school."},
        {"fi": "Siskoni harrastaa balettia.", "en": "My sister practices ballet."},
        {"fi": "Meillä on iso puutarha.", "en": "We have a big garden."},
        {"fi": "Vaimoni on töissä sairaalassa.", "en": "My wife works at a hospital."},
        {"fi": "Mieheni kokkaa illallisen.", "en": "My husband cooks dinner."},
        {"fi": "Lapsenlapset tulevat käymään.", "en": "The grandchildren are coming to visit."},
        {"fi": "Äitini pitää kukista.", "en": "My mother likes flowers."},
        {"fi": "Isäni on eläkkeellä.", "en": "My father is retired."},
        {"fi": "Perheemme viettää joulua yhdessä.", "en": "Our family spends Christmas together."},
        {"fi": "Asumme rauhallisella alueella.", "en": "We live in a peaceful area."},
    ],
    "Leisure & sports": [
        {"fi": "Käyn kuntosalilla kolme kertaa viikossa.", "en": "I go to the gym three times a week."},
        {"fi": "Katsomme elokuvia viikonloppuisin.", "en": "We watch movies on weekends."},
        {"fi": "Soitan kitaraa vapaa-ajalla.", "en": "I play guitar in my free time."},
        {"fi": "Uin järvessä kesäisin.", "en": "I swim in the lake in summer."},
        {"fi": "Juoksen usein puistossa.", "en": "I often run in the park."},
        {"fi": "Osallistun maalauskurssille.", "en": "I attend a painting class."},
        {"fi": "Käymme kävelyllä iltaisin.", "en": "We go for a walk in the evenings."},
        {"fi": "Harrastan valokuvausta.", "en": "My hobby is photography."},
        {"fi": "Pelaamme lautapelejä perheen kanssa.", "en": "We play board games with the family."},
        {"fi": "Aion oppia tanssimaan.", "en": "I plan to learn to dance."},
        {"fi": "Rakastan ratsastusta.", "en": "I love horse riding."},
        {"fi": "Pelaan tennistä ystävieni kanssa.", "en": "I play tennis with my friends."},
        {"fi": "Kirjoitan päiväkirjaa iltaisin.", "en": "I write a diary in the evenings."},
        {"fi": "Käyn retkellä metsässä.", "en": "I go hiking in the forest."},
        {"fi": "Kokeilen uusia reseptejä keittiössä.", "en": "I try new recipes in the kitchen."},
        {"fi": "Luemme kirjoja yhdessä.", "en": "We read books together."},
        {"fi": "Osallistun musiikkikonserttiin.", "en": "I attend a music concert."},
        {"fi": "Piirrän luonnoksia vihkoon.", "en": "I draw sketches in a notebook."},
        {"fi": "Katson jalkapallo-otteluita televisiosta.", "en": "I watch football matches on TV."},
        {"fi": "Purjehdimme kesällä järvellä.", "en": "We sail on the lake in the summer."},
    ],
    "At the doctor/pharmacy": [
        {"fi": "Haluan varata ajan hammaslääkärille.", "en": "I want to book a dentist appointment."},
        {"fi": "Olen ottanut lääkkeen jo tänään.", "en": "I have already taken the medicine today."},
        {"fi": "Voitko kuvata oireet tarkemmin?", "en": "Can you describe the symptoms in more detail?"},
        {"fi": "Onko sinulla resepti mukana?", "en": "Do you have the prescription with you?"},
        {"fi": "Miten voin auttaa sinua paremmin?", "en": "How can I help you better?"},
        {"fi": "Voitko täyttää tämän lomakkeen?", "en": "Can you fill out this form?"},
        {"fi": "Oletko käyttänyt tätä lääkettä ennen?", "en": "Have you used this medicine before?"},
        {"fi": "Tarvitsetko uutta reseptiä?", "en": "Do you need a new prescription?"},
        {"fi": "Seuraa ohjeita tarkasti.", "en": "Follow the instructions carefully."},
        {"fi": "Ota yhteyttä lääkäriin, jos oireet jatkuvat.", "en": "Contact a doctor if the symptoms continue."},
        {"fi": "Missä on lääkärin vastaanotto?", "en": "Where is the doctor's office?"},
        {"fi": "Minulla on vatsakipua.", "en": "I have stomach pain."},
        {"fi": "Tarvitsen kipulääkettä.", "en": "I need pain medicine."},
        {"fi": "Olen allerginen penisilliinille.", "en": "I am allergic to penicillin."},
        {"fi": "Onko tämä lääke saatavilla?", "en": "Is this medicine available?"},
        {"fi": "Voinko puhua lääkärin kanssa?", "en": "Can I speak with the doctor?"},
        {"fi": "Milloin voin hakea lääkkeen?", "en": "When can I pick up the medicine?"},
        {"fi": "Minulla on flunssan oireita.", "en": "I have flu symptoms."},
        {"fi": "Tarvitsetko sairauslomatodistuksen?", "en": "Do you need a sick leave certificate?"},
        {"fi": "Voitko mitata kuumeen?", "en": "Can you take my temperature?"},
    ],


}

@app.route('/')
def index():
    return render_template('index.html', themes=list(FLASHCARDS.keys()))

@app.route('/start_session', methods=['POST'])
def start_session():
    theme = request.json['theme']
    session['theme'] = theme
    session['shown'] = []
    session['correct'] = 0
    session['wrong'] = 0
    return jsonify({"total": len(FLASHCARDS[theme])})

@app.route('/get_card')
def get_card():
    theme = session.get('theme')
    shown = session.get('shown', [])
    available = [i for i in range(len(FLASHCARDS[theme])) if i not in shown]
    if not available:
        return jsonify({"end": True, "correct": session.get('correct', 0), "wrong": session.get('wrong', 0), "total": len(FLASHCARDS[theme])})
    idx = random.choice(available)
    session['current_idx'] = idx
    session.modified = True
    return jsonify({"fi": FLASHCARDS[theme][idx]['fi'], "en": FLASHCARDS[theme][idx]['en'], "progress": len(shown)+1, "total": len(FLASHCARDS[theme])})

@app.route('/mark', methods=['POST'])
def mark():
    knew = request.json['knew']
    theme = session.get('theme')
    idx = session.get('current_idx')
    if idx not in session['shown']:
        session['shown'].append(idx)
        if knew:
            session['correct'] += 1
        else:
            session['wrong'] += 1
    session.modified = True
    return jsonify({"progress": len(session['shown']), "total": len(FLASHCARDS[theme]), "correct": session['correct'], "wrong": session['wrong']})

@app.route('/restart')
def restart():
    session.clear()
    return jsonify({"ok": True})

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000)
    app.run(debug=True)